"""empty message

Revision ID: fa638759d0e9
Revises: b5cd8da92ea7
Create Date: 2020-12-14 17:12:05.068186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa638759d0e9'
down_revision = 'b5cd8da92ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fyyur', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('fyyur_genre_venue_id_fkey', 'fyyur', type_='foreignkey')
    op.create_foreign_key(None, 'fyyur', 'artist', ['artist_id'], ['id'])
    op.drop_column('fyyur', 'genre_venue_id')
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.add_column('fyyur', sa.Column('genre_venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fyyur', type_='foreignkey')
    op.create_foreign_key('fyyur_genre_venue_id_fkey', 'fyyur', 'genre_venue', ['genre_venue_id'], ['id'])
    op.drop_column('fyyur', 'artist_id')
    op.create_table('genre_venue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='genre_venue_pkey')
    )
    # ### end Alembic commands ###
